name: "Build"
on:
  pull_request:
    types: [review_requested, ready_for_review]
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '12.x'
        distribution: 'adopt'
    - uses: subosito/flutter-action@v2.10.0
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk --debug
